services:
  rabbit:
    image: "rabbitmq:3.13-management"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - bank_net

  configserver:
    image: "mcelism/bank-configserver:v1.0"
    container_name: configserver
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "2"
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    networks:
      - bank_net

  accounts:
    image: "mcelism/bank-accounts:v1.0"
    container_name: accounts_api
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "2"
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    networks:
      - bank_net

  loans:
    image: "mcelism/bank-loans:v1.0"
    container_name: loans_api
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
          cpus: "2"
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_APPLICATION_NAME: "loans"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    networks:
      - bank_net

  cards:
    image: "mcelism/bank-cards:v1.0"
    container_name: "cards_api"
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
          cpus: "2"
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_APPLICATION_NAME: "cards"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    networks:
      - bank_net


networks:
  bank_net:
    driver: "bridge"